apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-cluster-zookeeper
  namespace: openshift-gitops
spec:
  destination:
    namespace: kafka-zookeeper-example
    server: "https://kubernetes.default.svc"
  source:
    path: 20-kafka-cluster-zookeeper
    repoURL: "https://github.com/dbgjerez/openshift-kafka-examples.git"
    targetRevision: main
  project: openshift-kafka-examples
  syncPolicy:
    syncOptions:
    - CreateNamespace=true