apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-console
  namespace: openshift-gitops
spec:
  destination:
    namespace: kafka
    server: "https://kubernetes.default.svc"
  source:
    path: 30-console
    repoURL: "https://github.com/dbgjerez/openshift-kafka-examples.git"
    targetRevision: main
  project: openshift-kafka-examples