apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-user
  namespace: openshift-gitops
spec:
  destination:
    namespace: kafka-kraft-example
    server: "https://kubernetes.default.svc"
  source:
    path: 50-kafka-user
    repoURL: "https://github.com/dbgjerez/openshift-kafka-examples.git"
    targetRevision: main
  project: openshift-kafka-examples
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
