apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  labels:
    strimzi.io/cluster: kafka-kraft
  name: kafka-nodepool
spec:
  replicas: 3
  resources:
    limits:
      cpu: '2'
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 2Gi
  roles:
    - broker
    - controller
  storage:
    type: ephemeral