apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-kraft
  annotations:
    strimzi.io/kraft: "enabled"
    strimzi.io/node-pools: "enabled"
spec:
  kafka:
    version: 3.9.0
    metadataVersion: '3.9'
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      auto.create.topics.enable: "true"
      default.replication.factor: 2
      min.insync.replicas: 2
      offsets.topic.replication.factor: 2
  entityOperator:
    topicOperator: {}
    userOperator: {}
