apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  labels:
    strimzi.io/cluster: kafka-kraft
  name: dborrego
spec:
  authentication:
    type: tls
  authorization:
    acls:
      - host: '*'
        operations:
          - Read
          - Describe
          - Write
          - Create
        resource:
          name: new-user
          patternType: literal
          type: topic
      - host: '*'
        operations:
          - Read
        resource:
          name: ms-send-mail
          patternType: literal
          type: group
    type: simple